### ISSUE TITLE
Running Import-Systems-FromCSV.ps1, Add-CentrifySetMember.ps1 throws exception

### ISSUE THREAD

**Issue by dhufford** [centrify/powershell-sdk#18]
The import-systems-fromCSV.ps1 script uses a csv file to import the system resources into Privilege Access Service. When filling out the CSV file you are able to add the Sets where the resources should be located within the Resource Sets Menu. When running this script with the Sets included an exception is being thrown by the Add-CentrifySetMember.ps1 script which is called by the Import-Systems-FromCSV.ps1. 

The sets have been pre-created and permissions for the user have been applied as such: View, Edit.

If you remove the sets from the csv file the script runs fine and adds the resources to Privilege Access Service and sets the permissions accordingly for the user against the systems being added.

![image](https://user-images.githubusercontent.com/37636086/129232676-51cfabc6-7bd4-491d-a478-8e8db8d225c5.png)

-OS: Server 2019
-Powershell: 5.0
-Module Version: 1.14.0712

**Comment by badrogh** [comment]
The error from Add-CentrifySetMember is indicating data was not found: "The requested data or its dependent data was not found in the service". This is likely due to Server being added as member of the Set not been found, where I understand at this point in the script it should have been created.
Before to drill into the sample script, let's eliminate issue with Add-CentrifySetMember cmdlet. Can you try adding the Server as member of the Set manually?
Something like, 
`Add-CentrifySetMember -CentrifySet (Get-VaultSystemSet -Name "Test Servers") -VaultSystem (Get-VaultSystem -Name "TESTSRV001")`

**Comment by badrogh** [comment]
Fixed issue in Add-CentrifySetMember where Json query was incorrect when adding members to Sets.
